import {
    ActivePromiseCount,
    ConcurrencyLimit,
    FreeSlots,
    FrequencyLimit,
    PromisePoolGroup,
    PromisePoolGroupOptions,
} from "./group";

export interface InvocationLimit {
    /**
     * Limits the number of times the generator function will be invoked.
     */
    invocationLimit: number;
}

export interface TaskOptionsBase {
    /**
     * An array of groups, each of which can be used to impose additional restrictions of the task, or a subset of
     * tasks within the pool. Groups can also be used to respond to the completion of larger tasks comprised of
     * smaller task components.
     */
    groups?: PromisePoolGroup[];
    /**
     * Starts the task in a paused state if set to true.
     */
    paused?: boolean;
}

export interface GenericTaskOptionsBase extends PromisePoolGroupOptions, TaskOptionsBase, Partial<InvocationLimit> { }

export interface GenericTaskOptions<R> extends GenericTaskOptionsBase {
    /**
     * Function used for creating promises to run.
     * This function will be run repeatedly until it returns undefined or the concurrency or invocation limit is
     * reached.
     * @param invocation The invocation number for this call, starting at 0 and incrementing by 1 for each call.
     */
    generator: (this: PromisePoolTask<any[]>, invocation: number) => Promise<R> | undefined | void;
}

export interface GenericTaskConvertedOptions<I, R> extends GenericTaskOptionsBase {
    generator: (this: PromisePoolTask<any>, invocation: number) => Promise<I> | undefined | void;
    resultConverter: (result: I[]) => R;
}

export enum TaskState {
    /**
     * The task is active promises will be generated by the pool according to the limits set.
     */
    Active,
    /**
     * The task is paused and may be ended or resumed later. Any outstanding promises will continue to run.
     */
    Paused,
    /**
     * The task has completed all the work provided by the generator. The task will terminate when all outstanding
     * promises have ended.
     */
    Exhausted,
    /**
     * All outstanding promises have ended and the result has been returned or an error thrown.
     */
    Terminated,
}

export interface TaskStateProperty {
    readonly state: TaskState;
}

export interface PromisePoolTask<R> extends
    InvocationLimit, ConcurrencyLimit, FrequencyLimit, ActivePromiseCount, FreeSlots, TaskStateProperty {
    readonly invocations: number;
    pause(): void;
    resume(): void;
    end(): void;
    promise(): Promise<R>;
}
